# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FlatEngine_Core_config = debug
  FlatEngine_Editor_config = debug
  FlatEngine_Runtime_config = debug

else ifeq ($(config),release)
  FlatEngine_Core_config = release
  FlatEngine_Editor_config = release
  FlatEngine_Runtime_config = release

else ifeq ($(config),dist)
  FlatEngine_Core_config = dist
  FlatEngine_Editor_config = dist
  FlatEngine_Runtime_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := FlatEngine-Core FlatEngine-Editor FlatEngine-Runtime

.PHONY: all clean help $(PROJECTS) Core

all: $(PROJECTS)

Core: FlatEngine-Core

FlatEngine-Core:
ifneq (,$(FlatEngine_Core_config))
	@echo "==== Building FlatEngine-Core ($(FlatEngine_Core_config)) ===="
	@${MAKE} --no-print-directory -C FlatEngine-Core -f Makefile config=$(FlatEngine_Core_config)
endif

FlatEngine-Editor: FlatEngine-Core
ifneq (,$(FlatEngine_Editor_config))
	@echo "==== Building FlatEngine-Editor ($(FlatEngine_Editor_config)) ===="
	@${MAKE} --no-print-directory -C FlatEngine-Editor -f Makefile config=$(FlatEngine_Editor_config)
endif

FlatEngine-Runtime: FlatEngine-Core
ifneq (,$(FlatEngine_Runtime_config))
	@echo "==== Building FlatEngine-Runtime ($(FlatEngine_Runtime_config)) ===="
	@${MAKE} --no-print-directory -C FlatEngine-Runtime -f Makefile config=$(FlatEngine_Runtime_config)
endif

clean:
	@${MAKE} --no-print-directory -C FlatEngine-Core -f Makefile clean
	@${MAKE} --no-print-directory -C FlatEngine-Editor -f Makefile clean
	@${MAKE} --no-print-directory -C FlatEngine-Runtime -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FlatEngine-Core"
	@echo "   FlatEngine-Editor"
	@echo "   FlatEngine-Runtime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"